server:
    port:8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri:
                    search-paths: config-data
    application:
        name: config-microservice
        
