server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/wilssondubon/blautechTest-microservices
                    search-paths: config-data
    application:
        name: config-microservice

